### ISSUE TITLE
Sample does not build

### ISSUE THREAD

**Issue by n8armstrong** [NativeScript/sample-ios-embedded#3]
Compiling with Xcode 9.0 fails (not sure about earlier versions of Xcode).

![screen shot 2017-09-26 at 2 54 58 pm](https://user-images.githubusercontent.com/1187499/30883890-e319f05c-a2ca-11e7-9063-f0fceba0dbc1.png)

**Comment by bootstraponline** [comment]
It looks like this issue has now been resolved. The ticket can be closed.

**Comment by jzilske** [comment]
@bootstraponline @NickIliev Can you tell how this has been resolved? I'm seeing similar issues while trying to integrate NativeScript into an existing iOS app... (cf. https://github.com/NativeScript/ios-runtime/issues/798)

**Comment by bootstraponline** [comment]
We switched to react native so I don't know if this was ever solved.
